echo Returning from the ashes to live another day…
cd ~/Desktop/eco
echo Compiling...
javac -cp .:lib/* src/**/*.java
echo Compiled...
cd ~/Desktop/eco/src
sleep 1
echo Running…
java -cp .:../lib/* -Djava.library.path=../native eco/Main
